import os
import openai
from PIL import Image
import streamlit as st
import speech_recognition as sr

api_key = st.sidebar.text_input("API Key", type="password")

openai.api_key = api_key

def capture_speech():
    rec = sr.Recognizer()
    with sr.Microphone() as mic:
        audio = rec.listen(mic)
    try:
        text = rec.recognize_google(audio)
    except:
        text = 'Not captured'
    return text

def openai_image(prompt):
    response = openai.Image.create(
        prompt=prompt,
        n=1,
        size="256x256"
    )
    image_url = response['data'][0]['url']
    return image_url



st.title("Image Generator")

st.write("Enter text or click the microphone icon to capture speech and generate captivating visuals with our user-friendly interface.")

text_input = st.text_input("Text Input", "")
speech_button = st.button("🎤 Capture Speech")

if text_input.strip() != "":
    input_text = text_input
elif speech_button:
    with st.spinner("Listening... 🎙️"):
        input_text = capture_speech()
        st.write("Speech captured:", input_text)
else:
    input_text = ""

if input_text.strip() != "":
    with st.spinner("Loading... 💫"):
        image_url = openai_image(input_text)
        st.image(image_url, caption='Generated by OpenAI')
elif speech_button:
    st.warning("Please capture speech first! ⚠")
